set_attack_value(AT_DAIR, AG_CATEGORY, 1)

set_attack_value(AT_DAIR, AG_SPRITE, sprite_get("dair"))
set_attack_value(AT_DAIR, AG_HURTBOX_SPRITE, sprite_get("dair"))

set_attack_value(AT_DAIR, AG_NUM_WINDOWS, 13)
//set_attack_value(AT_DAIR, AG_HAS_LANDING_LAG, 1)

set_window_value(AT_DAIR, 1, AG_WINDOW_LENGTH, 18)
set_window_value(AT_DAIR, 1, AG_WINDOW_ANIM_FRAMES, 3)
set_window_value(AT_DAIR, 1, AG_WINDOW_HSPEED, 0)
set_window_value(AT_DAIR, 1, AG_WINDOW_VSPEED, 0)
set_window_value(AT_DAIR, 1, AG_WINDOW_HSPEED_TYPE, 1)
set_window_value(AT_DAIR, 1, AG_WINDOW_VSPEED_TYPE, 1)

set_window_value(AT_DAIR, 2, AG_WINDOW_TYPE, 8)
set_window_value(AT_DAIR, 2, AG_WINDOW_LENGTH, 100)
set_window_value(AT_DAIR, 2, AG_WINDOW_ANIM_FRAMES, 2)
set_window_value(AT_DAIR, 2, AG_WINDOW_ANIM_FRAME_START, 3)
set_window_value(AT_DAIR, 2, AG_WINDOW_HSPEED, 6)
set_window_value(AT_DAIR, 2, AG_WINDOW_VSPEED, 20)
set_window_value(AT_DAIR, 2, AG_WINDOW_HSPEED_TYPE, 1)
set_window_value(AT_DAIR, 2, AG_WINDOW_VSPEED_TYPE, 1)
set_window_value(AT_DAIR, 2, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_DAIR, 2, AG_WINDOW_SFX, asset_get("sfx_dash_start"))

set_window_value(AT_DAIR, 3, AG_WINDOW_LENGTH, 20)
set_window_value(AT_DAIR, 3, AG_WINDOW_ANIM_FRAMES, 10)
set_window_value(AT_DAIR, 3, AG_WINDOW_ANIM_FRAME_START, 24)
set_window_value(AT_DAIR, 3, AG_WINDOW_HSPEED, 0)
set_window_value(AT_DAIR, 3, AG_WINDOW_HSPEED_TYPE, 1)

set_window_value(AT_DAIR, 4, AG_WINDOW_LENGTH, 30)
set_window_value(AT_DAIR, 4, AG_WINDOW_ANIM_FRAMES, 5)
set_window_value(AT_DAIR, 4, AG_WINDOW_ANIM_FRAME_START, 5)
set_window_value(AT_DAIR, 4, AG_WINDOW_CUSTOM_GRAVITY, 1)
set_window_value(AT_DAIR, 4, AG_WINDOW_HSPEED, 0)
set_window_value(AT_DAIR, 4, AG_WINDOW_VSPEED, 0)
set_window_value(AT_DAIR, 4, AG_WINDOW_HSPEED_TYPE, 1)
set_window_value(AT_DAIR, 4, AG_WINDOW_VSPEED_TYPE, 1)

// set_window_value(AT_DAIR, 5, AG_WINDOW_LENGTH, 18)
// set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAMES, 6)
// set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAME_START, 10)
// set_window_value(AT_DAIR, 5, AG_WINDOW_CUSTOM_GRAVITY, 1)
// set_window_value(AT_DAIR, 5, AG_WINDOW_HSPEED, -4)
// set_window_value(AT_DAIR, 5, AG_WINDOW_VSPEED, -14)
// set_window_value(AT_DAIR, 5, AG_WINDOW_HSPEED_TYPE, 2)
// set_window_value(AT_DAIR, 5, AG_WINDOW_VSPEED_TYPE, 2)

set_window_value(AT_DAIR, 5, AG_WINDOW_LENGTH, 3)
set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DAIR, 5, AG_WINDOW_ANIM_FRAME_START, 10)
set_window_value(AT_DAIR, 5, AG_WINDOW_CUSTOM_GRAVITY, 1)
set_window_value(AT_DAIR, 5, AG_WINDOW_HSPEED, -4)
set_window_value(AT_DAIR, 5, AG_WINDOW_VSPEED, -14)
set_window_value(AT_DAIR, 5, AG_WINDOW_HSPEED_TYPE, 2)
set_window_value(AT_DAIR, 5, AG_WINDOW_VSPEED_TYPE, 2)

set_window_value(AT_DAIR, 7, AG_WINDOW_LENGTH, 3)
set_window_value(AT_DAIR, 7, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DAIR, 7, AG_WINDOW_ANIM_FRAME_START, 11)

set_window_value(AT_DAIR, 8, AG_WINDOW_LENGTH, 3)
set_window_value(AT_DAIR, 8, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DAIR, 8, AG_WINDOW_ANIM_FRAME_START, 12)

set_window_value(AT_DAIR, 9, AG_WINDOW_LENGTH, 3)
set_window_value(AT_DAIR, 9, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DAIR, 9, AG_WINDOW_ANIM_FRAME_START, 13)

set_window_value(AT_DAIR, 10, AG_WINDOW_LENGTH, 3)
set_window_value(AT_DAIR, 10, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DAIR, 10, AG_WINDOW_ANIM_FRAME_START, 14)

set_window_value(AT_DAIR, 11, AG_WINDOW_LENGTH, 3)
set_window_value(AT_DAIR, 11, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DAIR, 11, AG_WINDOW_ANIM_FRAME_START, 15)

set_window_value(AT_DAIR, 12, AG_WINDOW_TYPE, 8)
set_window_value(AT_DAIR, 12, AG_WINDOW_LENGTH, 100)
set_window_value(AT_DAIR, 12, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DAIR, 12, AG_WINDOW_ANIM_FRAME_START, 16)

set_window_value(AT_DAIR, 13, AG_WINDOW_LENGTH, 21)
set_window_value(AT_DAIR, 13, AG_WINDOW_ANIM_FRAMES, 7)
set_window_value(AT_DAIR, 13, AG_WINDOW_ANIM_FRAME_START, 17)
set_window_value(AT_DAIR, 13, AG_WINDOW_HSPEED, -2)
set_window_value(AT_DAIR, 13, AG_WINDOW_HSPEED_TYPE, 1)

set_num_hitboxes(AT_DAIR, 2)

set_hitbox_value(AT_DAIR, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_DAIR, 1, HG_WINDOW, 2)
set_hitbox_value(AT_DAIR, 1, HG_LIFETIME, 100)
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_X, 10)
set_hitbox_value(AT_DAIR, 1, HG_HITBOX_Y, -40)
set_hitbox_value(AT_DAIR, 1, HG_WIDTH, 50)
set_hitbox_value(AT_DAIR, 1, HG_HEIGHT, 70)
set_hitbox_value(AT_DAIR, 1, HG_PRIORITY, 4)
set_hitbox_value(AT_DAIR, 1, HG_BASE_KNOCKBACK, 4)
set_hitbox_value(AT_DAIR, 1, HG_EXTRA_HITPAUSE, 20)
set_hitbox_value(AT_DAIR, 1, HG_HIT_SFX, asset_get("sfx_clairen_nspecial_grab_success"))

set_hitbox_value(AT_DAIR, 2, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_DAIR, 2, HG_WINDOW, 13)
set_hitbox_value(AT_DAIR, 2, HG_LIFETIME, 2)
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_X, -40)
set_hitbox_value(AT_DAIR, 2, HG_HITBOX_Y, -40)
set_hitbox_value(AT_DAIR, 2, HG_WIDTH, 80)
set_hitbox_value(AT_DAIR, 2, HG_HEIGHT, 80)
set_hitbox_value(AT_DAIR, 2, HG_SHAPE, 1)
set_hitbox_value(AT_DAIR, 2, HG_PRIORITY, 4)
set_hitbox_value(AT_DAIR, 2, HG_DAMAGE, 22)
set_hitbox_value(AT_DAIR, 2, HG_ANGLE, 105)
set_hitbox_value(AT_DAIR, 2, HG_BASE_KNOCKBACK, 7)
set_hitbox_value(AT_DAIR, 2, HG_KNOCKBACK_SCALING, 1.2)
set_hitbox_value(AT_DAIR, 2, HG_BASE_HITPAUSE, 6)
set_hitbox_value(AT_DAIR, 2, HG_HITPAUSE_SCALING, .4)
set_hitbox_value(AT_DAIR, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy1"))
