set_attack_value(AT_DSPECIAL, AG_CATEGORY, 2)

set_attack_value(AT_DSPECIAL, AG_SPRITE, sprite_get("dspecial"))
set_attack_value(AT_DSPECIAL, AG_HURTBOX_SPRITE, sprite_get("dspecial"))

set_attack_value(AT_DSPECIAL, AG_NUM_WINDOWS, 4)

set_window_value(AT_DSPECIAL, 1, AG_WINDOW_LENGTH, 6)
set_window_value(AT_DSPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 3)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_SFX, asset_get("sfx_roll"))
//set_window_value(AT_DSPECIAL, 2, AG_WINDOW_SFX_FRAME, 2)

set_window_value(AT_DSPECIAL, 2, AG_WINDOW_LENGTH, 10)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_ANIM_FRAME_START, 3)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HSPEED, 16)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HSPEED_TYPE, 1)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_VSPEED, 0)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_HSPEED_TYPE, 1)
set_window_value(AT_DSPECIAL, 2, AG_WINDOW_INVINCIBILITY, 2)

set_window_value(AT_DSPECIAL, 3, AG_WINDOW_LENGTH, 12)
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_ANIM_FRAMES, 3)
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_ANIM_FRAME_START, 4)
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_HSPEED, 0)
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_HSPEED_TYPE, 2)
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"))
set_window_value(AT_DSPECIAL, 3, AG_WINDOW_SFX_FRAME, 2)

set_window_value(AT_DSPECIAL, 4, AG_WINDOW_LENGTH, 16)
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_ANIM_FRAMES, 8)
set_window_value(AT_DSPECIAL, 4, AG_WINDOW_ANIM_FRAME_START, 7)

set_num_hitboxes(AT_DSPECIAL, 1)

set_hitbox_value(AT_DSPECIAL, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_DSPECIAL, 1, HG_WINDOW, 4)
set_hitbox_value(AT_DSPECIAL, 1, HG_LIFETIME, 7)
set_hitbox_value(AT_DSPECIAL, 1, HG_HITBOX_X, 20)
set_hitbox_value(AT_DSPECIAL, 1, HG_HITBOX_Y, -65)
set_hitbox_value(AT_DSPECIAL, 1, HG_WIDTH, 100)
set_hitbox_value(AT_DSPECIAL, 1, HG_HEIGHT, 120)
// set_hitbox_value(AT_DSPECIAL, 1, HG_SHAPE, 1)
set_hitbox_value(AT_DSPECIAL, 1, HG_PRIORITY, 4)
set_hitbox_value(AT_DSPECIAL, 1, HG_DAMAGE, 10)
set_hitbox_value(AT_DSPECIAL, 1, HG_ANGLE, 80)
set_hitbox_value(AT_DSPECIAL, 1, HG_BASE_KNOCKBACK, 11)
set_hitbox_value(AT_DSPECIAL, 1, HG_BASE_HITPAUSE, 6)
set_hitbox_value(AT_DSPECIAL, 1, HG_KNOCKBACK_SCALING, .2)
set_hitbox_value(AT_DSPECIAL, 1, HG_HITPAUSE_SCALING, 0)
set_hitbox_value(AT_DSPECIAL, 1, HG_HITSTUN_MULTIPLIER, 1.2)
set_hitbox_value(AT_DSPECIAL, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"))
