set_attack_value(AT_DSTRONG, AG_SPRITE, sprite_get("dstrong"));
set_attack_value(AT_DSTRONG, AG_HURTBOX_SPRITE, sprite_get("dstrong_hurt"));

set_attack_value(AT_DSTRONG, AG_NUM_WINDOWS, 4)
set_attack_value(AT_DSTRONG, AG_STRONG_CHARGE_WINDOW, 1)

set_window_value(AT_DSTRONG, 1, AG_WINDOW_LENGTH, 10)
set_window_value(AT_DSTRONG, 1, AG_WINDOW_ANIM_FRAMES, 5)

set_window_value(AT_DSTRONG, 2, AG_WINDOW_LENGTH, 14)
set_window_value(AT_DSTRONG, 2, AG_WINDOW_ANIM_FRAMES, 9)
set_window_value(AT_DSTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 5)
set_window_value(AT_DSTRONG, 2, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_DSTRONG, 2, AG_WINDOW_SFX, sound_get("whip"))
set_window_value(AT_DSTRONG, 2, AG_WINDOW_SFX_FRAME, 10)

set_window_value(AT_DSTRONG, 3, AG_WINDOW_LENGTH, 13)
set_window_value(AT_DSTRONG, 3, AG_WINDOW_ANIM_FRAMES, 13)
set_window_value(AT_DSTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 14)
//set_window_value(AT_DSTRONG, 3, AG_WINDOW_HAS_WHIFFLAG, 1)

set_window_value(AT_DSTRONG, 4, AG_WINDOW_LENGTH, 12)
set_window_value(AT_DSTRONG, 4, AG_WINDOW_ANIM_FRAMES, 4)
set_window_value(AT_DSTRONG, 4, AG_WINDOW_ANIM_FRAME_START, 27)

set_num_hitboxes(AT_DSTRONG, 2)

set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_DSTRONG, 1, HG_WINDOW, 3)
set_hitbox_value(AT_DSTRONG, 1, HG_LIFETIME, 3)
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_X, 93)
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_Y, -20)
set_hitbox_value(AT_DSTRONG, 1, HG_WIDTH, 140)
set_hitbox_value(AT_DSTRONG, 1, HG_HEIGHT, 40)
set_hitbox_value(AT_DSTRONG, 1, HG_SHAPE, 2)
set_hitbox_value(AT_DSTRONG, 1, HG_PRIORITY, 4)
set_hitbox_value(AT_DSTRONG, 1, HG_DAMAGE, 10)
set_hitbox_value(AT_DSTRONG, 1, HG_ANGLE, 15)
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_KNOCKBACK, 5)
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_HITPAUSE, 8)
set_hitbox_value(AT_DSTRONG, 1, HG_KNOCKBACK_SCALING, .6)
set_hitbox_value(AT_DSTRONG, 1, HG_HITPAUSE_SCALING, 1)
set_hitbox_value(AT_DSTRONG, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"))

set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_DSTRONG, 2, HG_WINDOW, 3)
set_hitbox_value(AT_DSTRONG, 2, HG_LIFETIME, 3)
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_X, 158)
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_Y, -13)
set_hitbox_value(AT_DSTRONG, 2, HG_WIDTH, 16)
set_hitbox_value(AT_DSTRONG, 2, HG_HEIGHT, 16)
set_hitbox_value(AT_DSTRONG, 2, HG_PRIORITY, 5)
set_hitbox_value(AT_DSTRONG, 2, HG_DAMAGE, 16)
set_hitbox_value(AT_DSTRONG, 2, HG_ANGLE, 15)
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_KNOCKBACK, 7)
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_HITPAUSE, 10)
set_hitbox_value(AT_DSTRONG, 2, HG_KNOCKBACK_SCALING, 1.0)
set_hitbox_value(AT_DSTRONG, 2, HG_HITPAUSE_SCALING, 1.4)
set_hitbox_value(AT_DSTRONG, 2, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"))
