set_attack_value(AT_DTILT, AG_SPRITE, sprite_get("dtilt"))
set_attack_value(AT_DTILT, AG_HURTBOX_SPRITE, sprite_get("dtilt"))

set_attack_value(AT_DTILT, AG_NUM_WINDOWS, 3)

set_window_value(AT_DTILT, 1, AG_WINDOW_LENGTH, 6)
set_window_value(AT_DTILT, 1, AG_WINDOW_ANIM_FRAMES, 6)
set_window_value(AT_DTILT, 1, AG_WINDOW_HSPEED, 5)
set_window_value(AT_DTILT, 1, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_DTILT, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"))

set_window_value(AT_DTILT, 2, AG_WINDOW_LENGTH, 4)
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAMES, 2)
set_window_value(AT_DTILT, 2, AG_WINDOW_ANIM_FRAME_START, 6)

set_window_value(AT_DTILT, 3, AG_WINDOW_LENGTH, 10)
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAMES, 5)
set_window_value(AT_DTILT, 3, AG_WINDOW_ANIM_FRAME_START, 8)
set_window_value(AT_DTILT, 3, AG_WINDOW_HAS_WHIFFLAG, 1)

set_num_hitboxes(AT_DTILT, 1)

set_hitbox_value(AT_DTILT, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_DTILT, 1, HG_WINDOW, 2)
set_hitbox_value(AT_DTILT, 1, HG_LIFETIME, 4)
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_X, 42)
set_hitbox_value(AT_DTILT, 1, HG_HITBOX_Y, -14)
set_hitbox_value(AT_DTILT, 1, HG_WIDTH, 60)
set_hitbox_value(AT_DTILT, 1, HG_HEIGHT, 42)
set_hitbox_value(AT_DTILT, 1, HG_PRIORITY, 3)
set_hitbox_value(AT_DTILT, 1, HG_DAMAGE, 6)
set_hitbox_value(AT_DTILT, 1, HG_ANGLE, 40)
set_hitbox_value(AT_DTILT, 1, HG_BASE_KNOCKBACK, 5)
set_hitbox_value(AT_DTILT, 1, HG_KNOCKBACK_SCALING, .4)
set_hitbox_value(AT_DTILT, 1, HG_BASE_HITPAUSE, 6)
set_hitbox_value(AT_UTILT, 3, HG_HITPAUSE_SCALING, .4)
set_hitbox_value(AT_DTILT, 1, HG_HIT_SFX, asset_get("sfx_blow_weak1"))