set_attack_value(AT_FSTRONG, AG_SPRITE, sprite_get("fstrong"));
set_attack_value(AT_FSTRONG, AG_HURTBOX_SPRITE, sprite_get("fstrong_hurt"));

set_attack_value(AT_FSTRONG, AG_NUM_WINDOWS, 3)
set_attack_value(AT_FSTRONG, AG_STRONG_CHARGE_WINDOW, 1)

set_window_value(AT_FSTRONG, 1, AG_WINDOW_LENGTH, 8)
set_window_value(AT_FSTRONG, 1, AG_WINDOW_ANIM_FRAMES, 2)

set_window_value(AT_FSTRONG, 2, AG_WINDOW_LENGTH, 10)
set_window_value(AT_FSTRONG, 2, AG_WINDOW_ANIM_FRAMES, 5)
set_window_value(AT_FSTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 2)
set_window_value(AT_FSTRONG, 2, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_FSTRONG, 2, AG_WINDOW_SFX, sound_get("whip"))
set_window_value(AT_FSTRONG, 2, AG_WINDOW_SFX_FRAME, 5)

set_window_value(AT_FSTRONG, 3, AG_WINDOW_LENGTH, 30)
set_window_value(AT_FSTRONG, 3, AG_WINDOW_ANIM_FRAMES, 17)
set_window_value(AT_FSTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 7)
//set_window_value(AT_FSTRONG, 3, AG_WINDOW_HAS_WHIFFLAG, 1)

set_num_hitboxes(AT_FSTRONG, 2)

set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_FSTRONG, 1, HG_WINDOW, 3)
set_hitbox_value(AT_FSTRONG, 1, HG_LIFETIME, 3)
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_X, 110)
set_hitbox_value(AT_FSTRONG, 1, HG_HITBOX_Y, -30)
set_hitbox_value(AT_FSTRONG, 1, HG_WIDTH, 140)
set_hitbox_value(AT_FSTRONG, 1, HG_HEIGHT, 60)
set_hitbox_value(AT_FSTRONG, 1, HG_SHAPE, 2)
set_hitbox_value(AT_FSTRONG, 1, HG_PRIORITY, 4)
set_hitbox_value(AT_FSTRONG, 1, HG_DAMAGE, 10)
set_hitbox_value(AT_FSTRONG, 1, HG_ANGLE, 35)
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_KNOCKBACK, 6)
set_hitbox_value(AT_FSTRONG, 1, HG_BASE_HITPAUSE, 8)
set_hitbox_value(AT_FSTRONG, 1, HG_KNOCKBACK_SCALING, .6)
set_hitbox_value(AT_FSTRONG, 1, HG_HITPAUSE_SCALING, .8)
set_hitbox_value(AT_FSTRONG, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"))

set_hitbox_value(AT_FSTRONG, 2, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_FSTRONG, 2, HG_WINDOW, 3)
set_hitbox_value(AT_FSTRONG, 2, HG_LIFETIME, 3)
set_hitbox_value(AT_FSTRONG, 2, HG_HITBOX_X, 178)
set_hitbox_value(AT_FSTRONG, 2, HG_HITBOX_Y, -18)
set_hitbox_value(AT_FSTRONG, 2, HG_WIDTH, 16)
set_hitbox_value(AT_FSTRONG, 2, HG_HEIGHT, 16)
set_hitbox_value(AT_FSTRONG, 2, HG_PRIORITY, 5)
set_hitbox_value(AT_FSTRONG, 2, HG_DAMAGE, 16)
set_hitbox_value(AT_FSTRONG, 2, HG_ANGLE, 35)
set_hitbox_value(AT_FSTRONG, 2, HG_BASE_KNOCKBACK, 7)
set_hitbox_value(AT_FSTRONG, 2, HG_BASE_HITPAUSE, 10)
set_hitbox_value(AT_FSTRONG, 2, HG_KNOCKBACK_SCALING, 1.0)
set_hitbox_value(AT_FSTRONG, 2, HG_HITPAUSE_SCALING, 1.4)
set_hitbox_value(AT_FSTRONG, 2, HG_HIT_SFX, asset_get("sfx_clairen_tip_strong"))