set_attack_value(AT_UAIR, AG_CATEGORY, 1)
set_attack_value(AT_UAIR, AG_HAS_LANDING_LAG, 1)
set_attack_value(AT_UAIR, AG_LANDING_LAG, 4)

set_attack_value(AT_UAIR, AG_SPRITE, sprite_get("uair"))
set_attack_value(AT_UAIR, AG_HURTBOX_SPRITE, sprite_get("uair"))

set_attack_value(AT_UAIR, AG_NUM_WINDOWS, 3)

set_window_value(AT_UAIR, 1, AG_WINDOW_LENGTH, 8)
set_window_value(AT_UAIR, 1, AG_WINDOW_ANIM_FRAMES, 4)
set_window_value(AT_UAIR, 1, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX, asset_get("sfx_swipe_medium1"))
set_window_value(AT_UAIR, 1, AG_WINDOW_SFX_FRAME, 5)

set_window_value(AT_UAIR, 2, AG_WINDOW_LENGTH, 1)
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_UAIR, 2, AG_WINDOW_ANIM_FRAME_START, 4)

set_window_value(AT_UAIR, 3, AG_WINDOW_LENGTH, 12)
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAMES, 5)
set_window_value(AT_UAIR, 3, AG_WINDOW_ANIM_FRAME_START, 5)

set_num_hitboxes(AT_UAIR, 4)

set_hitbox_value(AT_UAIR, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_UAIR, 1, HG_WINDOW, 2)
set_hitbox_value(AT_UAIR, 1, HG_LIFETIME, 5)
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_X, 40)
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_Y, -40)
set_hitbox_value(AT_UAIR, 1, HG_WIDTH, 34)
set_hitbox_value(AT_UAIR, 1, HG_HEIGHT, 36)
set_hitbox_value(AT_UAIR, 1, HG_PRIORITY, 3)
set_hitbox_value(AT_UAIR, 1, HG_DAMAGE, 10)
set_hitbox_value(AT_UAIR, 1, HG_ANGLE, 80)
set_hitbox_value(AT_UAIR, 1, HG_BASE_KNOCKBACK, 7)
set_hitbox_value(AT_UAIR, 1, HG_KNOCKBACK_SCALING, .8)
set_hitbox_value(AT_UAIR, 1, HG_BASE_HITPAUSE, 5)
set_hitbox_value(AT_UAIR, 1, HG_HITPAUSE_SCALING, .5)
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT_X_OFFSET, 32)
set_hitbox_value(AT_UAIR, 1, HG_VISUAL_EFFECT_Y_OFFSET, -10)
set_hitbox_value(AT_UAIR, 1, HG_HIT_SFX, asset_get("sfx_blow_medium1"))
set_hitbox_value(AT_UAIR, 1, HG_ANGLE_FLIPPER, 6)
set_hitbox_value(AT_UAIR, 1, HG_HITBOX_GROUP, 1)

set_hitbox_value(AT_UAIR, 2, HG_PARENT_HITBOX, 1)
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_UAIR, 2, HG_WINDOW, 2)
set_hitbox_value(AT_UAIR, 2, HG_LIFETIME, 5)
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_X, 48)
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_Y, -70)
set_hitbox_value(AT_UAIR, 2, HG_HITBOX_GROUP, 1)

set_hitbox_value(AT_UAIR, 3, HG_PARENT_HITBOX, 1)
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_UAIR, 3, HG_WINDOW, 2)
set_hitbox_value(AT_UAIR, 3, HG_LIFETIME, 5)
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_X, 35)
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_Y, -95)
set_hitbox_value(AT_UAIR, 3, HG_HITBOX_GROUP, 1)

set_hitbox_value(AT_UAIR, 4, HG_PARENT_HITBOX, 1)
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_UAIR, 4, HG_WINDOW, 2)
set_hitbox_value(AT_UAIR, 4, HG_LIFETIME, 5)
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_X, 15)
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_Y, -105)
set_hitbox_value(AT_UAIR, 4, HG_HITBOX_GROUP, 1)
