set_attack_value(AT_USPECIAL, AG_CATEGORY, 2)

set_attack_value(AT_USPECIAL, AG_SPRITE, sprite_get("uspecial"))
set_attack_value(AT_USPECIAL, AG_HURTBOX_SPRITE, sprite_get("uspecial"))

set_attack_value(AT_USPECIAL, AG_NUM_WINDOWS, 3)

set_window_value(AT_USPECIAL, 1, AG_WINDOW_LENGTH, 8)
set_window_value(AT_USPECIAL, 1, AG_WINDOW_ANIM_FRAMES, 4)
set_window_value(AT_USPECIAL, 1, AG_WINDOW_INVINCIBILITY, 1)
set_window_value(AT_USPECIAL, 1, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_USPECIAL, 1, AG_WINDOW_SFX, asset_get("sfx_clairen_uspecial_rise"))

set_window_value(AT_USPECIAL, 2, AG_WINDOW_LENGTH, 24)
set_window_value(AT_USPECIAL, 2, AG_WINDOW_ANIM_FRAMES, 12)
set_window_value(AT_USPECIAL, 2, AG_WINDOW_ANIM_FRAME_START, 4)
set_window_value(AT_USPECIAL, 2, AG_WINDOW_HSPEED, 3)
set_window_value(AT_USPECIAL, 2, AG_WINDOW_VSPEED, -15)
set_window_value(AT_USPECIAL, 2, AG_WINDOW_VSPEED_TYPE, 2)
set_window_value(AT_USPECIAL, 2, AG_WINDOW_HSPEED_TYPE, 2)

set_window_value(AT_USPECIAL, 3, AG_WINDOW_TYPE, 7)
set_window_value(AT_USPECIAL, 3, AG_WINDOW_ANIM_FRAMES, 1)
set_window_value(AT_USPECIAL, 3, AG_WINDOW_ANIM_FRAME_START, 16)

set_num_hitboxes(AT_USPECIAL, 4)

set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_USPECIAL, 1, HG_WINDOW, 2)
set_hitbox_value(AT_USPECIAL, 1, HG_LIFETIME, 4)
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_X, 4)
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_Y, -55)
set_hitbox_value(AT_USPECIAL, 1, HG_WIDTH, 90)
set_hitbox_value(AT_USPECIAL, 1, HG_HEIGHT, 100)
set_hitbox_value(AT_USPECIAL, 1, HG_PRIORITY, 3)
set_hitbox_value(AT_USPECIAL, 1, HG_DAMAGE, 4)
set_hitbox_value(AT_USPECIAL, 1, HG_ANGLE, 80)
set_hitbox_value(AT_USPECIAL, 1, HG_BASE_KNOCKBACK, 15)
set_hitbox_value(AT_USPECIAL, 1, HG_KNOCKBACK_SCALING, 0)
set_hitbox_value(AT_USPECIAL, 1, HG_BASE_HITPAUSE, 6)
set_hitbox_value(AT_USPECIAL, 1, HG_HITPAUSE_SCALING, 0)
set_hitbox_value(AT_USPECIAL, 1, HG_HIT_SFX, asset_get("sfx_blow_weak1"))
set_hitbox_value(AT_USPECIAL, 1, HG_ANGLE_FLIPPER, 6)
set_hitbox_value(AT_USPECIAL, 1, HG_HITBOX_GROUP, 1)

set_hitbox_value(AT_USPECIAL, 2, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_USPECIAL, 2, HG_WINDOW, 2)
set_hitbox_value(AT_USPECIAL, 2, HG_WINDOW_CREATION_FRAME, 4)
set_hitbox_value(AT_USPECIAL, 2, HG_LIFETIME, 4)
set_hitbox_value(AT_USPECIAL, 2, HG_HITBOX_X, 4)
set_hitbox_value(AT_USPECIAL, 2, HG_HITBOX_Y, -70)
set_hitbox_value(AT_USPECIAL, 2, HG_WIDTH, 110)
set_hitbox_value(AT_USPECIAL, 2, HG_HEIGHT, 100)
set_hitbox_value(AT_USPECIAL, 2, HG_PRIORITY, 3)
set_hitbox_value(AT_USPECIAL, 2, HG_DAMAGE, 4)
set_hitbox_value(AT_USPECIAL, 2, HG_ANGLE, 80)
set_hitbox_value(AT_USPECIAL, 2, HG_BASE_KNOCKBACK, 12)
set_hitbox_value(AT_USPECIAL, 2, HG_KNOCKBACK_SCALING, .1)
set_hitbox_value(AT_USPECIAL, 2, HG_BASE_HITPAUSE, 6)
set_hitbox_value(AT_USPECIAL, 2, HG_HITPAUSE_SCALING, 0)
set_hitbox_value(AT_USPECIAL, 2, HG_HIT_SFX, asset_get("sfx_blow_weak1"))
set_hitbox_value(AT_USPECIAL, 2, HG_ANGLE_FLIPPER, 6)
set_hitbox_value(AT_USPECIAL, 2, HG_HITBOX_GROUP, 2)

set_hitbox_value(AT_USPECIAL, 3, HG_PARENT_HITBOX , 2)
set_hitbox_value(AT_USPECIAL, 3, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_USPECIAL, 3, HG_WINDOW, 2)
set_hitbox_value(AT_USPECIAL, 3, HG_WINDOW_CREATION_FRAME, 8)
set_hitbox_value(AT_USPECIAL, 3, HG_LIFETIME, 4)
set_hitbox_value(AT_USPECIAL, 3, HG_HITBOX_X, 4)
set_hitbox_value(AT_USPECIAL, 3, HG_HITBOX_Y, -75)
set_hitbox_value(AT_USPECIAL, 3, HG_HITBOX_GROUP, 2)

set_hitbox_value(AT_USPECIAL, 4, HG_PARENT_HITBOX , 2)
set_hitbox_value(AT_USPECIAL, 4, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_USPECIAL, 4, HG_WINDOW, 2)
set_hitbox_value(AT_USPECIAL, 4, HG_WINDOW_CREATION_FRAME, 12)
set_hitbox_value(AT_USPECIAL, 4, HG_LIFETIME, 4)
set_hitbox_value(AT_USPECIAL, 4, HG_HITBOX_X, 4)
set_hitbox_value(AT_USPECIAL, 4, HG_HITBOX_Y, -75)
set_hitbox_value(AT_USPECIAL, 4, HG_HITBOX_GROUP, 3)