set_attack_value(AT_USTRONG, AG_SPRITE, sprite_get("ustrong"))
set_attack_value(AT_USTRONG, AG_HURTBOX_SPRITE, sprite_get("ustrong"))

set_attack_value(AT_USTRONG, AG_NUM_WINDOWS, 4)
set_attack_value(AT_USTRONG, AG_STRONG_CHARGE_WINDOW, 1)

set_window_value(AT_USTRONG, 1, AG_WINDOW_LENGTH, 12)
set_window_value(AT_USTRONG, 1, AG_WINDOW_ANIM_FRAMES, 3)

set_window_value(AT_USTRONG, 2, AG_WINDOW_LENGTH, 3)
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAMES, 3)
set_window_value(AT_USTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 3)
set_window_value(AT_USTRONG, 2, AG_WINDOW_HAS_SFX, 1)
set_window_value(AT_USTRONG, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"))

set_window_value(AT_USTRONG, 3, AG_WINDOW_LENGTH, 3)
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAMES, 3)
set_window_value(AT_USTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 6)

set_window_value(AT_USTRONG, 4, AG_WINDOW_LENGTH, 30)
set_window_value(AT_USTRONG, 4, AG_WINDOW_ANIM_FRAMES, 10)
set_window_value(AT_USTRONG, 4, AG_WINDOW_ANIM_FRAME_START, 9)
set_window_value(AT_USTRONG, 4, AG_WINDOW_HAS_WHIFFLAG, 1)

set_num_hitboxes(AT_USTRONG, 2)

set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_USTRONG, 1, HG_WINDOW, 3)
set_hitbox_value(AT_USTRONG, 1, HG_LIFETIME, 4)
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_X, 30)
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_Y, -65)
set_hitbox_value(AT_USTRONG, 1, HG_WIDTH, 60)
set_hitbox_value(AT_USTRONG, 1, HG_HEIGHT, 84)
set_hitbox_value(AT_USTRONG, 1, HG_PRIORITY, 6)
set_hitbox_value(AT_USTRONG, 1, HG_DAMAGE, 14)
set_hitbox_value(AT_USTRONG, 1, HG_ANGLE, 85)
set_hitbox_value(AT_USTRONG, 1, HG_BASE_KNOCKBACK, 9)
set_hitbox_value(AT_USTRONG, 1, HG_BASE_HITPAUSE, 8)
set_hitbox_value(AT_USTRONG, 1, HG_KNOCKBACK_SCALING, 1.1)
set_hitbox_value(AT_USTRONG, 1, HG_HITPAUSE_SCALING, 1)
set_hitbox_value(AT_USTRONG, 1, HG_HIT_SFX, asset_get("sfx_blow_heavy1"))
set_hitbox_value(AT_USTRONG, 1, HG_HITBOX_GROUP, 1)

set_hitbox_value(AT_USTRONG, 2, HG_PARENT_HITBOX, 1)
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_TYPE, 1)
set_hitbox_value(AT_USTRONG, 2, HG_WINDOW, 3)
set_hitbox_value(AT_USTRONG, 2, HG_LIFETIME, 4)
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_X, 5)
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_Y, -70)
set_hitbox_value(AT_USTRONG, 2, HG_WIDTH, 40)
set_hitbox_value(AT_USTRONG, 2, HG_HEIGHT, 60)
set_hitbox_value(AT_USTRONG, 2, HG_HITBOX_GROUP, 1)